FROM python:3.14-slim
ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app
COPY pyproject.toml ./
COPY src ./src
RUN pip install .
RUN useradd --create-home app
USER app
CMD ["python", "-m", "{{PKG}}"]
